Consistent engine error handling
flimlib/flimlib pull request #52
Opened 2021-08-27 23:04 UTC by facetorched

Error handling was not consistent between fitting engines. The fitting engines should return negative error codes if the tries reaches maxrefits and the chi squared target has still not been acheived. 

Furthermore, I fixed what I belive is a bug with `GCI_marquardt_fitting_engine` in that positive and negative error codes were summed and returned. This could result in a failed fit appearing like a success and vice-versa depending on the numbers summed. If the inner loop of the engine encounters an error, the engine should give up and raise that same error code. I would like to confirm with @ctrueden that this behaviour makes sense.

2021-08-28 03:08 UTC, ctrueden commented
@facetorched I'm sorry, I don't know the correct behavior. @paulbarber can likely comment here, though.

2021-08-28 16:34 UTC, marktsuchida requested changes
The change in the last commit changes the return value of `GCI_marquardt_fitting_engine()` in the successful case: it is no longer the sum of inner iterations. I think you need a new variable to keep count of total iterations so that it can be returned.

2021-08-28 16:35 UTC, marktsuchida commented
I'm pretty sure this change makes sense and is correct (once my above review comment is addressed), but I'd also appreciate a comment from @paulbarber.

2021-08-31 10:52 UTC, paulbarber commented
Hi @facetorched this makes sense. I will only say that with commit  211e29cf8ac953dea2fee38d6c1031cbbeca2490 the returned value is no longer the sum of all tries, so I agree with @marktsuchida .

2021-09-03 18:03 UTC, marktsuchida approved these changes

2021-09-03 18:03 UTC, merged